services:
  server:
    build: bullseye/
    ports: 
      - "8211:8211"
      - "25575:25575"
    env_file:
      - ./default.env
    volumes:
      - "$HOST_MOUNT:/home/steam/palworld-dedicated/Pal/Saved"
